apiVersion: apps/v1
kind: Deployment
metadata:
  name: Keyvaultterraformapp-deployment
spec:
  selector:
    matchLabels:
      app: Keyvaultterraformapp
  template:
    metadata:
      labels:
        app: Keyvaultterraformapp
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: Keyvaultterraformapp-serviceaccount
      containers:
        - name: Keyvaultterraformapp
          image: ordercontainerregistry.azurecr.io/Keyvaultterraformapp:1.0.1
          ports:
            - containerPort: 5002
          env:
            - name: KeyVaultSetting__Url
              value: https://myorderkeyvault.vault.azure.net/
           
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
            requests:
              memory: "128Mi"
              cpu: "150m"
      restartPolicy: Always
  

